import Head from 'next/head'
import {map} from "lodash"
import {Box, Button, Grid, GridItem, Image, Stack, Text} from "@chakra-ui/react"
import Navbar from "@components/Navbar";
import ApartmentSimpleCard from "@containers/ApartmentSimpleCard";
import FilterSection from "@components/FilterSection";

const Home = () => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <Navbar/>
            <Box
                position='relative'
                px="10rem"
                zIndex={1}
                marginTop={20}>
                <Grid
                    marginTop={7}
                    width='100%'
                    templateColumns="200px 1fr"
                    gap={5}
                >
                    <FilterSection/>
                    <Grid
                        width='100%'
                        height="87vh"
                        overflowY='scroll'
                        templateColumns="repeat(3, 1fr)"
                        gap={5}
                    >
                        {
                            map([1, 2, 3, 4, 5,6,7,8,9,10,11,12], item => (
                                <ApartmentSimpleCard key={item}/>
                            ))
                        }
                    </Grid>
                </Grid>
            </Box>
        </>
    )
}

export default Home
